apiVersion: v1
kind: Service
metadata:
  namespace: tp2
  name: devcalc-cluster-svc
spec:
  selector:
    app: devcalc-api
  type: ClusterIP
  ports:
    - name: http
      port: 8081
      targetPort: 80
  