apiVersion: v1
kind: Service
metadata:
  namespace: tp2
  name: devcalc-node-svc
spec:
  selector:
    app: devcalc-api
  type: NodePort
  ports:
    - name: http
      port: 8081
      targetPort: 80
      nodePort: 30003
  