apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tp2
  name: devcalc-deployment
spec:
  selector:
    matchLabels:
      app: devcalc-api
  replicas: 2
  template:
    metadata:
      labels:
        app: devcalc-api
    spec:
      containers:
      - name: devcalc-api
        image: nginx:1.29.3-alpine-slim
        ports:
        - containerPort: 80
